version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Tokyo
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Tokyo
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /infra/ansible
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Asia/Tokyo
    groups:
      ansible:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: /infra/terraform
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Tokyo
    groups:
      terraform:
        patterns:
          - "*"
